version: '3.8'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phone-codes
      SPRING_DATASOURCE_USERNAME: vanyamanko
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - db

  db:
    image: postgres:14.11
    environment:
      DATABASE_PORT: 5432
      POSTGRES_USER: vanyamanko
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: phone-codes
    expose:
      - 5432
