version: '3.8'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://roundhouse.proxy.rlwy.net:35451/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: BuXulRaBvuXoZRcuLQcMRxmapVjhBxJT
    depends_on:
      - db

  db:
    image: postgres:14.11
    environment:
      DATABASE_PORT: 5432
      POSTGRES_USER: vanyamanko
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: phone-codes
    expose:
      - 5432

  frontend-react:
    container_name: frontend
    build: ../countries-parameters-client
    ports:
      - "3000:3000"
